---
- name: Rulebook to print debug message based on webhook event
  hosts: testHost
  gather_facts: false

  sources:
      - ansible.eda.webhook:
          host: localhost
          port: 6000

  rules:
      - name: Launch playbook on commit
        condition: event.payload.action == 'created'
        action:
           run_job_template:
               name: MyProject_IIS
               extra_vars:
                   eventSource: "{{ eventSource }}"  
