- name: Listen for events
  hosts: all
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 6000
  rules:
    - name: Rule - Print event information
    condition: event.meta.headers is defined
    action:
      run_job_template:
        name: MyProject_IIS
        organization: Default
        job_args:
          extra_vars:
             message: from eda
             sleep: 1
